[
    {
      "country": "Nigeria",
      "association_name": "NSF",
      "chairman": "",
      "secretary": "",
      "contact": "Chief Toke Aka",
      "facebook": "NigeriaScrabbleFederation",
      "twitter": "NigeriaScrabbleFederation",
      "instagram": "",
      "website": "www.nigeriascrabble.com/",
      "ranked_players": 114,
      "top_panasa_ranked": "Wellington Jighere",
      "image_url": "flagnga.png"
    },
    {
      "country": "Ghana",
      "association_name": "Scrabble Association of Ghana",
      "chairman": "",
      "secretary": "",
      "contact": "Michael Quao",
      "facebook": "Scrabble Association of Ghana (SCAG)",
      "twitter": "scrabbleghana",
      "instagram": "PanScrabble",
      "website": "",
      "ranked_players": 12,
      "top_panasa_ranked": "Charles Tachie-Menson",
      "image_url": "flaggha.png"
    },
    {
      "country": "Kenya",
      "association_name": "Scrabble Kenya",
      "chairman": "Benard Amuke",
      "secretary": "",
      "contact": "Benard Amuke (Chairman)",
      "facebook": "ScrabbleKenya",
      "twitter": "Scrabble_Kenya",
      "instagram": "",
      "website": "www.scrabblekenya.com/",
      "ranked_players": 58,
      "top_panasa_ranked": "Allan Oyende",
      "image_url": "flagken.png"
    },
    {
      "country": "Botswana",
      "association_name": "BOSCRA",
      "chairman": "Kemoneilwe Bonno",
      "secretary": "",
      "contact": "Kemoneilwe Bonno (President)",
      "facebook": "Botswana.BOSCRA",
      "twitter": "",
      "instagram": "",
      "website": "",
      "ranked_players": 0,
      "top_panasa_ranked": "",
      "image_url": "flagbot.png"
    },
    {
      "country": "Liberia",
      "association_name": "NASAL",
      "chairman": "",
      "secretary": "",
      "contact": "Fomba A. M. Swaray & Malek V. Al- Sherif",
      "facebook": "National Scrabble Association of Liberia (NASAL)",
      "twitter": "",
      "instagram": "",
      "website": "",
      "ranked_players": 1,
      "top_panasa_ranked": "Malek Sherif",
      "image_url": "flaglbr.png"
    },
    {
      "country": "Sierra Leone",
      "association_name": "NSASL",
      "chairman": "",
      "secretary": "",
      "contact": "Rowland Tom",
      "facebook": "NSASL - The National Scrabble Association of Sierra Leone",
      "twitter": "",
      "instagram": "",
      "website": "",
      "ranked_players": 4,
      "top_panasa_ranked": "Mohamed Kamara",
      "image_url": "flagsie.png"
    },
    {
      "country": "Tanzania",
      "association_name": "TASPA",
      "chairman": "",
      "secretary": "",
      "contact": "Dr Mushtak Esmail",
      "facebook": "scrabble Tanzania",
      "twitter": "",
      "instagram": "",
      "website": "",
      "ranked_players": 6,
      "top_panasa_ranked": "Dr Mushtak Esmail",
      "image_url": "flagtan.png"
    },
    {
      "country": "Zambia",
      "association_name": "ZAM",
      "chairman": "",
      "secretary": "",
      "contact": "",
      "facebook": "",
      "twitter": "",
      "instagram": "",
      "website": "",
      "ranked_players": 0,
      "top_panasa_ranked": "",
      "image_url": "flagzam.png"
    },
    {
      "country": "Uganda",
      "association_name": "Scrabble Association of Uganda",
      "chairman": "",
      "secretary": "",
      "contact": "Chris Ntege",
      "facebook": "Scrabble_ASC",
      "twitter": "ScrabbleUganda",
      "instagram": "",
      "website": "www.ugandascrabble.com/",
      "ranked_players": 22,
      "top_panasa_ranked": "Geria Richard",
      "image_url": "flaguga.png"
    },
    {
      "country": "South Africa",
      "association_name": "Scrabble South Africa",
      "chairman": "Andrew Goldberg",
      "secretary": "",
      "contact": "Steven Gruzd",
      "facebook": "Scrabble SA",
      "twitter": "Scrabble_SA",
      "instagram": "Scrabblesouthafrica",
      "website": "www.zascrabble.com/",
      "ranked_players": 22,
      "top_panasa_ranked": "Trevor Hovelmeier",
      "image_url": "flagzaf.png"
    }
  ]
  